// <auto-generated />
using HalloWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HalloWeb.Migrations
{
    [DbContext(typeof(HalloWebContext))]
    partial class HalloWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HalloWeb.Models.Klopapier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnzahlBlatt")
                        .HasColumnType("int");

                    b.Property<string>("Duft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hersteller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Langen")
                        .HasColumnType("int");

                    b.Property<string>("Produkt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klopapier");
                });
#pragma warning restore 612, 618
        }
    }
}
